apiVersion: apps/v1
kind: Deployment
metadata:
  name: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
        - name: add
          image: ghcr.io/cage1016/ms-sample-add
          env:
            - name: QS_GRPC_PORT
              value: "10021"
            - name: QS_HTTP_PORT
              value: "10020"
            - name: QS_LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 0
---
kind: Service
apiVersion: v1
metadata:
  name: add
spec:
  selector:
    app: add
  ports:
    - port: 80
      name: http
      targetPort: 10020
    - port: 8000
      name: grpc
      targetPort: 10021
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: titac-pvc
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-postgres-configuration
  labels:
    app: ms-postgres
data:
  POSTGRES_DB: tictac
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictac
  template:
    metadata:
      labels:
        app: tictac
    spec:
      volumes:
        - name: ms-postgresdb-storage
          persistentVolumeClaim:
            claimName: titac-pvc
      containers:
        - image: postgres:9.6.3
          name: my-database
          envFrom:
          - configMapRef:
              name: ms-postgres-configuration
          ports:
          - containerPort: 5432
          resources: {}
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data:Z"
            name: ms-postgresdb-storage
        - name: tictac
          image: ghcr.io/cage1016/ms-sample-tictac
          env:
            - name: QS_DB
              value: "tictac"
            - name: QS_DB_HOST
              value: "localhost"
            - name: QS_DB_PASS
              value: "password"
            - name: QS_DB_PORT
              value: "5432"
            - name: QS_DB_SSL_CERT
              value: ""
            - name: QS_DB_SSL_KEY
              value: ""
            - name: QS_DB_SSL_MODE
              value: ""
            - name: QS_DB_SSL_ROOT_CERT
              value: ""
            - name: QS_DB_USER
              value: "postgres"
            - name: QS_GRPC_PORT
              value: "10121"
            - name: QS_HTTP_PORT
              value: "10120"
            - name: QS_LOG_LEVEL
              value: "info"
            - name: QS_ADD_URL
              value: "add:8000"
---
kind: Service
apiVersion: v1
metadata:
  name: tictac
spec:
  selector:
    app: tictac
  ports:
    - port: 80
      name: http
      targetPort: 10120
    - port: 8000
      name: grpc
      targetPort: 10121