apiVersion: apps/v1
kind: Deployment
metadata:
  name: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:        
        - name: add
          image: ghcr.io/cage1016/ms-sample-add
          env:
            - name: QS_GRPC_PORT
              value: "10021"
            - name: QS_HTTP_PORT
              value: "10020"
            - name: QS_LOG_LEVEL
              value: "info"              
          ports:
            - containerPort: 10021
          readinessProbe:
            exec:
              command: ["/layers/cage1016_github-assets-cnb/github-assets/bin/grpc_health_probe", "-addr=:10021"]
            initialDelaySeconds: 5
          livenessProbe:           
            exec:
              command: ["/layers/cage1016_github-assets-cnb/github-assets/bin/grpc_health_probe", "-addr=:10021"]
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 0
---
kind: Service
apiVersion: v1
metadata:
  name: add
spec:
  selector:
    app: add
  ports:
    - port: 80
      name: http
      targetPort: 10020
    - port: 8000
      name: grpc
      targetPort: 10021