kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: titac-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "100Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-postgres-configuration
  labels:
    app: ms-postgres
data:
  POSTGRES_DB: tictac
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictac
  template:
    metadata:
      labels:
        app: tictac
    spec:
      volumes:
        - name: ms-postgresdb-storage
          persistentVolumeClaim:
            claimName: titac-pvc
      containers:
        - image: postgres:9.6.3
          name: my-database
          envFrom:
          - configMapRef:
              name: ms-postgres-configuration
          ports:
          - containerPort: 5432
          resources: {}
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: ms-postgresdb-storage
        - name: tictac
          image: ms-sample-tictac
          env:
            - name: QS_DB
              value: "tictac"
            - name: QS_DB_HOST
              value: "localhost"
            - name: QS_DB_PASS
              value: "password"
            - name: QS_DB_PORT
              value: "5432"
            - name: QS_DB_SSL_CERT
              value: ""
            - name: QS_DB_SSL_KEY
              value: ""
            - name: QS_DB_SSL_MODE
              value: "disable"
            - name: QS_DB_SSL_ROOT_CERT
              value: ""
            - name: QS_DB_USER
              value: "postgres"
            - name: QS_GRPC_PORT
              value: "10121"
            - name: QS_HTTP_PORT
              value: "10120"
            - name: QS_LOG_LEVEL
              value: "info"
            - name: QS_ADD_URL
              value: "add:8000"
          ports:
          - containerPort: 10121
          readinessProbe:
            exec:
              command: ["/layers/cage1016_github-assets-cnb/grpc-ecosystem_grpc-health-probe/bin/grpc_health_probe", "-addr=:10121"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/layers/cage1016_github-assets-cnb/grpc-ecosystem_grpc-health-probe/bin/grpc_health_probe", "-addr=:10121"]
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 0            
---
kind: Service
apiVersion: v1
metadata:
  name: tictac
spec:
  selector:
    app: tictac
  ports:
    - port: 80
      name: http
      targetPort: 10120
    - port: 8000
      name: grpc
      targetPort: 10121

