[[metadata.githubassets]]
repo = "grpc-ecosystem/grpc-health-probe"
asset = "grpc_health_probe-linux-amd64"
destination = "bin/grpc_health_probe"

[[build.buildpacks]]
id = "google.go.runtime"
version = "0.9.1"

[[build.buildpacks]]
id = "google.go.build"
version = "0.9.0"

[[build.buildpacks]]
id = "google.utils.label"
version = "0.0.1"

[[build.buildpacks]]
id = "cage1016/github-assets-cnb"
version = "2.1.1"