# [[build.env]]
# optional, github token for private assets 
# name = "TOKEN"
# value = "<github-token>"

# skaffold
[[build.env]]
# required
name = "REPO"
value = "grpc-ecosystem/grpc-health-probe"

[[build.env]]
# required
name = "FILE"
value = "grpc_health_probe-linux-amd64"

[[build.env]]
# optional, default set to FILE value
name = "TARGET"
value = "grpc_health_probe"

# [[build.env]]
# # optional, default set to 'latest'
# name = "VERSION"
# value = "v1.22.0"

[[build.buildpacks]]
id = "google.go.runtime"
version = "0.9.1"

[[build.buildpacks]]
id = "google.go.build"
version = "0.9.0"

[[build.buildpacks]]
id = "google.utils.label"
version = "0.0.1"

[[build.buildpacks]]
id = "cage1016/github-assets-cnb"
version = "1.1.0"