[[metadata.githubassets]]
repo = "grpc-ecosystem/grpc-health-probe"
asset = "grpc_health_probe-linux-amd64"
destination = "bin/grpc_health_probe"

[[build.buildpacks]]
id = "google.go.runtime"

[[build.buildpacks]]
id = "google.go.build"

[[build.buildpacks]]
id = "google.utils.label"

[[build.buildpacks]]
id = "cage1016/github-assets-cnb"
version = "2.1.1"
