apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: ms-sample-add
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - GOOGLE_BUILDABLE=cmd/add/main.go
        projectDescriptor: project.toml
        dependencies:
          paths:
            - cmd/add/main.go
            - internal/app/add/**
            - internal/pkg/**
    - image: ms-sample-tictac
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - GOOGLE_BUILDABLE=cmd/tictac/main.go
        projectDescriptor: project.toml
        dependencies:
          paths:
            - cmd/tictac/main.go
            - internal/app/tictac/**
            - internal/pkg/**
  tagPolicy:
      sha256: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - ./deployments/kubernetes-manifests/*.yaml
