apiVersion: v1
kind: Service
metadata:
  name: add-external
  labels:
    app: add
spec:
  type: LoadBalancer
  selector:
    app: add
  ports:
  - port: 8180
    name: http
    targetPort: 10020
  - port: 8181
    name: grpc
    targetPort: 10021