apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /api/v1/add(/|$)(.*)
          backend:
            serviceName: add
            servicePort: 80
        - path: /api/v1/tictac(/|$)(.*)
          backend:
            serviceName: tictac
            servicePort: 80